---
- hosts: 172.31.21.224
  become: yes
  tasks: 
  - name: execute linux command
    command: hostname -f
    register: myfirsttaskresult

  - name: display my first task result
    debug:
      msg: "{{myfirsttaskresult}}"
