---
- hosts: 172.31.21.224
  become: yes
  tasks: 
  - name: execute linux command
    command: hostname -f
    register: myfirsttaskresult

  - name: display my first task result
    debug:
      msg: "{{myfirsttaskresult}}"

  - name: install git
    dnf:
     name: git
     when: myfirsttaskresult.stderr!=""

  - name: install tree
    dnf:
     name: tree
     when: myfirsttaskresult.stdett!=""
     


