---
- hosts: 172.31.21.224
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    dnf:
      name: httpd
      state: present
  - name: copy text file
    copy:
      src: mytestfile
      dest: /home/anil/mytestfile