---
- hosts: 172.31.21.224
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    dnf:
      name: httpd
      state: present
  - name: copy text file
    copy:
      src: mytestfile
      dest: /home/anil/mytestfile

  - name: download internet file
    get_url:
       url: https://adp-mirror-vm1-he-fi.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20-deployer.tar.gz
       dest: /home/anil/apache-tomcat-10.0.20-deployer.tar.gz
       force_basic_auth: yes 
